name: Deploy MNIST App

on:
  push:
    branches: [ main ]  # 或者您的主分支名稱
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # 使用您設置的自託管執行器
    
    steps:
    - name: Clean workspace
      run: |
        expect -c '
        spawn su -
        expect "Password: "
        send "P@ssw0rd\r"
        expect "#"
        send "rm -rf MNIST/ || true"
        expect eof
        '
  
    - name: Clone repository
      run: |
        git clone https://github.com/Marance776/MNIST.git
    
    - name: Build and deploy
      run: |
        # 使用 expect 命令自動提供 su 密碼
        expect -c '
        spawn su -
        expect "Password: "
        send "P@ssw0rd\r"
        expect "#"
        send "cd MNIST"
        expect "#"
        send "docker rmi mnist-app || true\r"
        expect "#"
        send "docker rmi easzlab.io.local:5000/mnist-app || true\r"
        expect "#"
        send "docker build -t mnist-app .\r"
        expect "#"
        send "docker image tag mnist-app easzlab.io.local:5000/mnist-app\r"
        expect "#"
        send "docker image push easzlab.io.local:5000/mnist-app\r"
        expect "#"
        send "kubectl delete -n default deployment mnist-app || true\r"
        expect "#"
        send "echo \"Waiting for 2 minutes before applying the new deployment...\"\r"
        expect "#"
        send "sleep 120\r"
        expect "#"
        send "kubectl apply -f mnist-app-deployment.yaml\r"
        expect "#"
        send "exit\r"
        expect eof
        '
