name: Deploy MNIST App

on:
  push:
    branches: [ main ]  # 或者您的主分支名稱
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # 使用您設置的自託管執行器
    
    steps:
    - name: Clean workspace
      run: |
        expect -c '
        spawn su -
        expect "#"
        send "rm -rf MNIST || true\r"
        expect eof
        '
  
    # - name: Clone repository
    #   run: |
    #     rm -rf MNIST || true
    #     git clone https://github.com/Marance776/MNIST.git
    #     sleep 60
    #     cd MNIST
    #     ls -a
    
    - name: Build and deploy
      run: |
        # 使用 expect 命令自動提供 su 密碼
        expect -c '
        set timeout -1
        spawn su -
        expect "~]#"
        send "rm -rf MNIST || true\r"
        expect "~]#"
        send "git clone https://github.com/Marance776/MNIST.git\r"
        expect "~]#"
        send "cd MNIST\r"
        expect "MNIST]# "
        send "ls -a\r"
        expect "MNIST]# "
        send "docker rmi mnist-app || true\r"
        expect "MNIST]# "
        send "docker rmi easzlab.io.local:5000/mnist-app || true\r"
        expect "MNIST]# "
        send "docker build -t mnist-app .\r"
        expect "MNIST]# "
        send "docker image tag mnist-app easzlab.io.local:5000/mnist-app\r"
        expect "MNIST]# "
        send "docker image push easzlab.io.local:5000/mnist-app\r"
        expect "MNIST]# "
        send "kubectl delete -n default deployment mnist-app || true\r"
        expect "MNIST]# "
        send "echo \"Waiting for 2 minutes before applying the new deployment...\"\r"
        expect "MNIST]# "
        send "kubectl apply -f mnist-app-deployment.yaml\r"
        expect "MNIST]# "
        send "exit\r"
        expect eof
        '
